"""Generates src/unicode_data.inc: the Unicode tables the tokenizers need (TOK-2).

    docker run --rm -v "$PWD":/w -w /w pulsatrix-lrpref:latest python3 tools/unicode/generate_unicode_data.py

- general categories, as sorted ranges (unlisted code points are Cn)
- canonical combining classes, as sorted ranges of nonzero classes
- canonical decompositions (one level; NFC decomposes recursively)
- canonical compositions: (first, second) -> composite, for primary composites only, i.e.
  compositions NFC actually makes (composition exclusions, singletons and non-starter
  decompositions left out)

Python 3.12's unicodedata is Unicode 15.0, the version of the Oniguruma that Hugging Face
`tokenizers` uses for its regexes. Hangul syllables are composed algorithmically, not tabled.
"""

import os
import unicodedata

CATEGORIES = ["Lu", "Ll", "Lt", "Lm", "Lo", "Mn", "Mc", "Me", "Nd", "Nl", "No", "Pc", "Pd", "Ps", "Pe",
              "Pi", "Pf", "Po", "Sm", "Sc", "Sk", "So", "Zs", "Zl", "Zp", "Cc", "Cf", "Cs", "Co", "Cn"]
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "src", "unicode_data.inc")
HANGUL = range(0xAC00, 0xD7A4)


def ranges(values):
    """[(start, end, value)] over code points whose value isn't None, merging equal neighbours."""
    out = []
    for cp, v in enumerate(values):
        if v is None:
            continue
        if out and out[-1][1] == cp - 1 and out[-1][2] == v:
            out[-1][1] = cp
        else:
            out.append([cp, cp, v])
    return out


def main():
    n = 0x110000
    cats = [unicodedata.category(chr(cp)) for cp in range(n)]
    cat_ranges = ranges([None if c == "Cn" else CATEGORIES.index(c) for c in cats])
    ccc_ranges = ranges([unicodedata.combining(chr(cp)) or None for cp in range(n)])

    decomp = {}
    for cp in range(n):
        if cp in HANGUL:
            continue
        d = unicodedata.decomposition(chr(cp))
        if d and not d.startswith("<"):
            decomp[cp] = [int(x, 16) for x in d.split()]
    comp = []
    for cp, parts in sorted(decomp.items()):
        if len(parts) == 2 and unicodedata.normalize("NFC", chr(parts[0]) + chr(parts[1])) == chr(cp):
            comp.append((parts[0], parts[1], cp))
    comp.sort()

    lines = ["// Generated by tools/unicode/generate_unicode_data.py from Unicode %s. Do not edit." % unicodedata.unidata_version,
             "// clang-format off",
             'constexpr const char* kUnicodeVersion = "%s";' % unicodedata.unidata_version,
             "constexpr CategoryRange kCategoryRanges[] = {"]
    lines += ["    {0x%X, 0x%X, %d}," % tuple(r) for r in cat_ranges]
    lines += ["};", "constexpr CombiningRange kCombiningRanges[] = {"]
    lines += ["    {0x%X, 0x%X, %d}," % tuple(r) for r in ccc_ranges]
    lines += ["};", "constexpr Decomposition kDecompositions[] = {"]
    lines += ["    {0x%X, {%s}, %d}," % (cp, ", ".join("0x%X" % p for p in parts + [0] * (4 - len(parts))), len(parts))
              for cp, parts in sorted(decomp.items())]
    lines += ["};", "constexpr Composition kCompositions[] = {"]
    lines += ["    {0x%X, 0x%X, 0x%X}," % c for c in comp]
    lines += ["};", "// clang-format on", ""]
    assert max(len(p) for p in decomp.values()) <= 4
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s: %d category ranges, %d combining ranges, %d decompositions, %d compositions"
          % (OUT, len(cat_ranges), len(ccc_ranges), len(decomp), len(comp)))


if __name__ == "__main__":
    main()
