var group__visualization =
[
    [ "json.hpp", "json_8hpp.html", null ],
    [ "attribution_bar_chart.hpp", "attribution__bar__chart_8hpp.html", null ],
    [ "attribution_beeswarm.hpp", "attribution__beeswarm_8hpp.html", null ],
    [ "attribution_graph.hpp", "attribution__graph_8hpp.html", null ],
    [ "attribution_waterfall.hpp", "attribution__waterfall_8hpp.html", null ],
    [ "circuit_graph_view.hpp", "circuit__graph__view_8hpp.html", null ],
    [ "colormap.hpp", "colormap_8hpp.html", null ],
    [ "confidence_meter.hpp", "confidence__meter_8hpp.html", null ],
    [ "dataset_statistics_view.hpp", "dataset__statistics__view_8hpp.html", null ],
    [ "document.hpp", "document_8hpp.html", null ],
    [ "explanation_score_card.hpp", "explanation__score__card_8hpp.html", null ],
    [ "fonts.hpp", "fonts_8hpp.html", null ],
    [ "html.hpp", "html_8hpp.html", null ],
    [ "image_grid_view.hpp", "image__grid__view_8hpp.html", null ],
    [ "implot_metrics_sink.hpp", "implot__metrics__sink_8hpp.html", null ],
    [ "mime_bundle.hpp", "mime__bundle_8hpp.html", null ],
    [ "plot_data.hpp", "plot__data_8hpp.html", null ],
    [ "protein_documents.hpp", "protein__documents_8hpp.html", null ],
    [ "protein_views.hpp", "protein__views_8hpp.html", null ],
    [ "report.hpp", "report_8hpp.html", null ],
    [ "saliency_heatmap_view.hpp", "saliency__heatmap__view_8hpp.html", null ],
    [ "svg.hpp", "svg_8hpp.html", null ],
    [ "text_relevance.hpp", "text__relevance_8hpp.html", null ],
    [ "texture_cache.hpp", "texture__cache_8hpp.html", null ],
    [ "token_relevance_view.hpp", "token__relevance__view_8hpp.html", null ],
    [ "training_dashboard.hpp", "training__dashboard_8hpp.html", null ],
    [ "window.hpp", "window_8hpp.html", null ]
];